apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-stable
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask-app
      version: stable
  template:
    metadata:
      labels:
        app: flask-app
        version: stable
    spec:
      containers:
        - name: flask
          image: sukanya996/flaskimg-app:blue
          ports:
            - containerPort: 5000
